[package]
name = "longcut-gui"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[dependencies]
itertools = "0.10.1"
longcut-core = { path = "../longcut-core" }
longcut-graphics-lib = { path = "../longcut-graphics-lib" }
