[package]
name = "ordinator"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = { version = "", features = ["v2_44"] }
gdk = { version = "", features = ["v3_22"] }
gtk = { version = "0.9.0", features = ["v3_22"] }
glib = { version = "", features = ["v2_44"] }
rand = "0.7.3"

