[workspace]
members = [
    "longcut-application",
    "longcut-config",
    "longcut-core",
    "longcut-gdk",
    "longcut-gui",
    "longcut-graphics-lib",
    "longcut-shell",
    "longcut-x11"
]
