[workspace]
resolver = "2"
members = [
    "longcut-gdk",
    "longcut-gdk/adapter-longcut-gui",
    "longcut-config",
    "longcut-shell",
    "longcut-shell/adapter-longcut-core",
    "longcut-graphics-lib",
    "longcut-x11",
    "longcut-x11/adapter-longcut-core",
    "longcut-application",
    "longcut-core",
    "longcut-gui",
    "longcut-gui/adapter-longcut-core",
]

[workspace.package]
authors = ["Sami Jokela"]
edition = "2021"
license = "GPL-3.0-or-later"
version = "0.1.0"

[workspace.dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
gdk = { version = "0.18", features = ["v3_24"] }
hex = "0.4.3"
itertools = "0.14.0"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.9.17"
serial_test = "3.2.0"
wait-timeout = "0.2.0"
x11 = { version = "2.18.2", features = ["xlib"] }
