[workspace]
resolver = "2"
members = [
    "longcut-gdk",
    "longcut-gdk/adapter-longcut-gui",
    "longcut-config",
    "longcut-shell",
    "longcut-shell/adapter-longcut-core",
    "longcut-graphics-lib",
    "longcut-x11",
    "longcut-x11/adapter-longcut-core",
    "longcut-application",
    "longcut-core",
    "longcut-gui",
    "longcut-gui/adapter-longcut-core",
]

[workspace.package]
authors = ["Sami Jokela"]
edition = "2021"
version = "0.1.0"
