[package]
name = "longcut-core"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
longcut-config = { path = "../longcut-config" }

itertools.workspace = true
regex.workspace = true
serde.workspace = true
