[package]
name = "longcut-core"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[dependencies]
longcut-config = { path = "../longcut-config" }
itertools = "0.10.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
