[package]
name = "longcut-core"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
longcut-config = { path = "../longcut-config" }
itertools = "0.10.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
