[package]
name = "longcut-x11-adapter-longcut-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
longcut-core = { path = "../../longcut-core" }
longcut-x11 = { path = ".." }
longcut-config = { path = "../../longcut-config" }

serde.workspace = true

[dev-dependencies]
serde_norway.workspace = true
