[package]
name = "longcut-x11-adapter-longcut-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
longcut-core = { path = "../../longcut-core" }
longcut-x11 = { path = ".." }

x11.workspace = true