[package]
name = "longcut-x11"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[dependencies]
longcut-core = { path = "../longcut-core" }
serial_test = "0.5.1"
x11 = { version = "2.18.2", features = ["xlib"] }
