[package]
name = "longcut-shell"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
longcut-config = { path = "../longcut-config" }
longcut-core = { path = "../longcut-core" }
serde = { version = "1.0.130", features = ["derive"] }
wait-timeout = "0.2.0"
