[package]
name = "longcut-shell"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
longcut-config = { path = "../longcut-config" }

serde.workspace = true
wait-timeout.workspace = true
