[package]
name = "longcut-shell"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[dependencies]
longcut-config = { path = "../longcut-config" }
longcut-core = { path = "../longcut-core" }
serde = { version = "1.0.130", features = ["derive"] }
wait-timeout = "0.2.0"
