[package]
name = "longcut-config"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
serde.workspace = true
serde_yaml.workspace = true
