[package]
name = "longcut-config"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
itertools = "0.10.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.9.17"
