[package]
name = "longcut-graphics-lib"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hex.workspace = true
itertools.workspace = true
