[package]
name = "longcut-gdk"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[dependencies]
gdk = { version = "0.14", features = ["v3_22"] }
longcut-config = { path = "../longcut-config" }
longcut-core = { path = "../longcut-core" }
longcut-gui = { path = "../longcut-gui" }
