[package]
name = "longcut-application"
version = "0.1.0"
authors = ["Sami Jokela"]
edition = "2021"

[[bin]]
name = "longcut"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.1", features = ["derive"] }
longcut-config = { path = "../longcut-config" }
longcut-core = { path = "../longcut-core" }
longcut-gdk = { path = "../longcut-gdk" }
longcut-gui = { path = "../longcut-gui" }
longcut-shell = { path = "../longcut-shell" }
longcut-x11 = { path = "../longcut-x11" }

