### Longcut test configuration

gui:
  font_family: sans-serif
  font_size: 16
  window_height: 360
  window_width: 880

core:
  keys_activate: alt_l
  keys_back: BackSpace
  keys_deactivate:
    - Escape
    - alt_l

  layers:
    - name: Error scenarios
      shortcut: e
      layers:
        - name: Async
          shortcut: a
          commands:
            - name: Command not found
              shortcut: "1"
              steps: thiscommandreallyshouldnotexist 1232123123
              synchronous: false
            - name: Invalid arguments
              shortcut: "2"
              steps: grep -A -R -C foo.txt
              synchronous: false
            - name: Exit code 1
              shortcut: "3"
              steps: sh -c "exit 1"
              synchronous: false

        - name: Sync
          shortcut: s
          commands:
            - name: Command not found
              shortcut: "1"
              steps: thiscommandreallyshouldnotexist 1232123123
            - name: Invalid arguments
              shortcut: "2"
              steps: grep -A -R -C foo.txt
            - name: Exit code 1, no log
              shortcut: "3"
              steps: sh -c "exit 1"
            - name: Exit code 2, stderr log
              shortcut: "4"
              steps: sh -c "echo Stderr >&2; exit 2"
            - name: Exit code 3, stdout log
              shortcut: "5"
              steps: sh -c "echo Stdout; exit 3"
            - name: Exit code 4, both logs
              shortcut: "6"
              steps: sh -c "echo Stdout; echo Stderr >&2; exit 4"

    - name: Parameter input
      shortcut: p
      commands:
        - name: Text parameter
          shortcut: "1"
          steps: echo "{0}"
          parameters:
            - name: Sample text
              type: text
        - name: Three texts
          shortcut: "2"
          steps:
            - echo "{0} {1} {2}"
          parameters:
            - name: First text
              type: text
            - name: Next text
              type: text
            - name: Final text
              type: text

shell:
  default_timeout_ms: 5000
